### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/pushcrew#5]
Hi @billmn

Are you still interested in maintaining this package?

If so, could we add support for laravel 5.5+ and 6.0?

Thanks!

**Comment by billmn** [comment]
Sure, I will update the package today

**Comment by billmn** [comment]
@atymic Done!

Unfortunately I haven't access to Travis and Scrutinizer and doesn't exists this package on Packagist.

Indeed al my badges are red (https://github.com/laravel-notification-channels/pushcrew/blob/master/README.md)

Can you help me with this?

**Comment by atymic** [comment]
Hey,
If this is the first version on packagist, is it worth renaming to to `vwo-engage` ?

**Comment by billmn** [comment]
@atymic Done 👍

**Comment by atymic** [comment]
Published to packagist:
https://packagist.org/packages/laravel-notification-channels/vwo-engage

**Comment by atymic** [comment]
Have added sensiolabs & scrutinizer as well

**Comment by billmn** [comment]
Nice, thanks. Can you also enable Travis CI?

**Comment by atymic** [comment]
Pretty sure travis is enabled.
https://travis-ci.org/laravel-notification-channels/vwo-engage/builds/591956711?utm_source=github_status&utm_medium=notification

**Comment by billmn** [comment]
Hi @atymic, I have completed all the updates and made a release.

I notice that the Symfony badge show “project not found” ... thoughts?

**Comment by atymic** [comment]
I've dropped the badge. It seems they no longer offer it free for open source (the one I tried to create was a private once, hence the badge wasn't accessible.

**Comment by billmn** [comment]
👍
